name: DynamicMarket
version: 1.0
main: com.example.economia.EconomiaPlugin
api-version: 1.13
depend: [Vault]

commands:
  market:
    description: Opens the market GUI
    usage: /market
  sell:
    description: Opens the sell GUI
    usage: /sell
  marketadmin:
    description: Admin commands for market management
    usage: /marketadmin
    permission: market.admin

permissions:
  market.admin:
    children:
      market.admin.reset: true
      market.admin.category: true
      market.admin.add: true
      market.admin.remove: true
      market.admin.setprice: true
      market.admin.move: true
  
  market.admin.category:
    description: Allows adding new categories
    default: op
  
  market.admin.add:
    description: Allows adding items to the market
    default: op
  
  market.admin.remove:
    description: Allows removing items from the market
    default: op
  
  market.admin.setprice:
    description: Allows changing item prices
    default: op
  
  market.admin.move:
    description: Allows moving items between categories
    default: op
  
  market.admin.reset:
    description: Allows resetting the market to default
    default: op