market_settings:
  min_price: 0.1
  max_price: 1000.0
  price_change_factor: 0.02

categories:
  "Ores and Minerals":
    icon: "DIAMOND"
    slot: 10
    items:
      COAL:
        buy_price: 1.0
        sell_price: 0.5
      IRON_INGOT:
        buy_price: 5.0
        sell_price: 3.0
      DIAMOND:
        buy_price: 100.0
        sell_price: 80.0

  "Building Blocks":
    icon: "STONE"
    slot: 12
    items:
      STONE:
        buy_price: 1.0
        sell_price: 0.5
      OAK_LOG:
        buy_price: 2.0
        sell_price: 1.0
      GLASS:
        buy_price: 3.0
        sell_price: 1.5

  "Food":
    icon: "BREAD"
    slot: 14
    items:
      BREAD:
        buy_price: 2.0
        sell_price: 1.0
      COOKED_BEEF:
        buy_price: 5.0
        sell_price: 3.0
      GOLDEN_APPLE:
        buy_price: 50.0
        sell_price: 30.0
